---
# file: awscli/tasks/main.yml
#
# tasks file
#

- include: debug.yml
  when: debug | default(false)
  tags: 
    - debug
    - never

- include: validation.yml
  tags: 
    - validation
    - never

- include: installation.yml
  tags: 
    - installation
    - never 
- include: configuration.yml
  tags: configuration
